### ISSUE TITLE
Bug with mixins

### ISSUE THREAD

**Issue by yoihito** [diogobaeder/pycket#10]
I was using SessionManage like a mixin. On every request, DriverFactory creates new client without closing previous. Because of this application handles to many CLOSE_WAIT sockets.
CentOS 6
Python 2.7.6
Tornado 3.2.1

**Comment by ppgoodman** [comment]
i find a bug,tornado set_secure_cookie expires must like time.time()+n second.so i modify __create_session_id:

**Comment by ppgoodman** [comment]
def __create_session_id(self):
        session_id = str(uuid4())
        cookie_settings = self.settings.get('cookies', {})
        __cookie_settings = copy.deepcopy(cookie_settings)
        if 'expires' in __cookie_settings:
            etime = __cookie_settings['expires']
            __cookie_settings['expires'] = time.time() + etime

        #cookie_settings.setdefault('expires', None)
        __cookie_settings.setdefault('expires_days', None)


        self.handler.set_secure_cookie(self.SESSION_ID_NAME, session_id,
                                       **__cookie_settings)
        return session_id

**Comment by diogobaeder** [comment]
**DISCONTINUED**

This library is not maintained anymore, hence won't receive any further support.
