### ISSUE TITLE
Ability to delete and replace a session mid-request. (help mitigate session fixation attacks)

### ISSUE THREAD

**Issue by miverson** [diogobaeder/pycket#9]
I'm thinking that there is a missing feature that is required to mitigate session fixation attacks. 

Best practices dictate that, upon authentication, the current session id should be deleted, and replaced with a new session id. While I could be mistaken, this should happen entirely within the post request to the auth method, once the user's credentials have passed validation. something like this:

```
    ...
    if newhash == pwdhash:
        # login success!
        self.session.regenerate_session_id()
        self.session.set(...
```

However, there is no present method to abandon the present session specified in the cookie sent in the request, and create a new session. Creating one seems fairly simple, and would look something like this:

```
# create method to delete and regenerate a session 
def regenerate_session_id(self):
    '''
    Delete all keys from current session, and generate a new session_id
    '''
    def change(session):
        keys = session.keys()
        for name in keys:
            del session[name]
    self.__change_session(change)
    id = self.__create_session_id()
```

The only wrinkle is that subsequent 'set()' and 'get()' requests will continue to 
read the session id from the old cookie value, as it is unaware that there is a new cookie pending. This could be surmounted editing '__get_session_id()'  to check if a new session cookie is pending in the response, and overriding the value of get_secure_cookie() as appropriate:

```
def __get_session_id(self):
    value = None
    if hasattr(self.handler, "_new_cookie") \
        and self.SESSION_ID_NAME in self.handler._new_cookie:
        value = self.handler._new_cookie[self.SESSION_ID_NAME].value

    session_id = self.handler.get_secure_cookie(self.SESSION_ID_NAME, value=value)
    if session_id is None:
        session_id = self.__create_session_id()
    return session_id

```

I've made a monkey-patch version of this code, and it seems to work as I've envisioned. 

Given all of this, here are some questions:
1. Am I completely off-base for thinking that this is a problem? In other words, am I solving a problem that does not really exist?
2. I'm a little uncomfortable accessing the private class member _new_cookie. Any alternate approaches that might work?
3. If your still with me at this point, are there any other dangers that I may be creating as a result of this change?

**Comment by diogobaeder** [comment]
**DISCONTINUED**

This library is not maintained anymore, hence won't receive any further support.
